### ISSUE TITLE
Recognise argparse.Namespace objects as collections in Configuration#set_args()

### ISSUE THREAD

**Issue by jackwilsdon** [sampsyo/confuse#33]
I started writing a solution for #32 when I came across this. It seems that confuse doesn't recognise `argparse.Namespace` objects as collections, which whilst never appearing normally should still be understood by confuse.

Here's an example of the issue:

``` Python
import argparse
import confuse


args = argparse.Namespace(
    first="Hello",
    nested=argparse.Namespace(
        second="World"
    )
)

configuration = confuse.Configuration('example', __name__)
configuration.set_args(args)

print(configuration['nested']['second'].get())
```

And the stack trace from the resulting error:

```
Traceback (most recent call last):
  File "example.py", line 15, in <module>
    print(configuration['nested']['second'].get())
  File "/usr/local/lib/python2.7/site-packages/confuse-0.4.0-py2.7.egg/confuse.py", line 385, in get
    return as_template(template).value(self, template)
  File "/usr/local/lib/python2.7/site-packages/confuse-0.4.0-py2.7.egg/confuse.py", line 980, in value
    if view.exists():
  File "/usr/local/lib/python2.7/site-packages/confuse-0.4.0-py2.7.egg/confuse.py", line 183, in exists
    self.first()
  File "/usr/local/lib/python2.7/site-packages/confuse-0.4.0-py2.7.egg/confuse.py", line 175, in first
    return iter_first(pairs)
  File "/usr/local/lib/python2.7/site-packages/confuse-0.4.0-py2.7.egg/confuse.py", line 59, in iter_first
    return next(it)
  File "/usr/local/lib/python2.7/site-packages/confuse-0.4.0-py2.7.egg/confuse.py", line 507, in resolve
    self.parent.name, type(collection).__name__
confuse.ConfigTypeError: nested must be a collection, not Namespace
```

I know we shouldn't really explicitly add `argparse.Namespace` as a collection, so maybe our collection detection logic needs some revamping? It might be an idea to try duck typing it first and then throwing a `confuse.ConfigTypeError` if that fails instead of just refusing the type in it's entirety.

**Comment by sampsyo** [comment]
Interesting point! Here's the relevant code, for the record, which is already somewhat duck-typed:

```py
try:
    value = collection[self.key]
# [...clip...]
except TypeError:
    # Not subscriptable.
    raise ConfigTypeError(
        u"{0} must be a collection, not {1}".format(
            self.parent.name, type(collection).__name__
        )
    )
```

We could, for example, try using `getattr(collection, self.key)` as a fallback when `collection[self.key]` doesn't work. That would make `Namespace` and related objects "just work" as collections.
